name: slow-tunes-bot

services:
  bot:
    image: slow-tunes-bot:2-alpha
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    mem_limit: 512m
    container_name: bot
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - redis
    environment:
      - TZ=Europe/Moscow
      - TMPDIR=/tmp
    cap_drop:
      - ALL
    cap_add:
      - SYS_RESOURCE
    read_only: true
    tmpfs:
      - /tmp:size=512m
    volumes:
      - bot-data:/app/data

  redis:
    container_name: redis
    image: redis:8-alpine
    init: true
    mem_limit: 16m
    restart: unless-stopped
    command: redis-server --save 300 1 --loglevel warning
    environment:
      - TZ=Europe/Moscow
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/redis
    volumes:
      - bot-cache:/data
volumes:
  bot-data:
  bot-cache:
