[project]
name = "slow-tunes-bot"
version = "2.0.0"
description = "Telegram Bot that slows down audio tracks yo 33/45 RPM vinyl ratio for dubious aesthetic pleasure"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.27.0",
    "aiosqlite>=0.22.1",
    "loguru>=0.7.3",
    "pydantic-settings>=2.13.1",
    "redis>=7.4.0",
    "sqlalchemy>=2.0.49",
]

[dependency-groups]
dev = ["ruff>=0.15.10"]

[tool.ruff]
exclude = ["venv", ".venv", "env", ".env"]
format.preview = true
line-length = 120
lint.select = ["ALL"]
lint.ignore = ["D", "ANN401", "SLF001", "INP001"]

[[tool.uv.index]]
name = "china"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[[tool.uv.index]]
name = "russia"
url = "https://mirror.yandex.ru/pypi/web/simple"
