CREATE TABLE IF NOT EXISTS match (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    original CHAR NOT NULL UNIQUE,
    slowed CHAR NOT NULL,
    user_id INTEGER NOT NULL,
    private BOOLEAN DEFAULT 1 NOT NULL,
    forbidden BOOLEAN DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    match_id INEGER NOT NULL,
    user_id INTEGER NOT NULL,
    UNIQUE (match_id, user_id)
);

CREATE TABLE IF NOT EXISTS queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL UNIQUE,
    count INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL UNIQUE,
    username CHAR NOT NULL
);
