from typing import Any, Protocol, TypeVar

ModelT = TypeVar("ModelT")


class AsyncStorageProtocol[ModelT](Protocol):
    async def save(self, obj: ModelT) -> ModelT: ...
    async def create(self, obj: ModelT) -> ModelT: ...
    async def delete(self, model: type[ModelT], **filters: Any) -> None: ...
    async def get(self, model: type[ModelT], pk: int) -> ModelT | None: ...
    async def get_by(self, model: type[ModelT], **filters: Any) -> ModelT | None: ...
    async def get_many(self, model: type[ModelT], *, limit: int, offset: int, **kwargs: Any) -> list[ModelT]: ...
    async def patch(self, model: type[ModelT], pk: int, data: dict[str, Any]) -> ModelT: ...
    async def count(self, model: type[ModelT], **filters: Any) -> int: ...
