from typing import Any, Protocol, TypeVar

T = TypeVar("T")  # model


class StorageProtocol(Protocol[T]):
    async def save(self, obj: T) -> T: ...
    async def create(self, obj: T) -> T: ...
    async def delete(self, model: type[T], **filters: Any) -> None: ...
    async def get(self, model: type[T], pk: int) -> T | None: ...
    async def get_by(self, model: type[T], **filters: Any) -> T | None: ...
    async def get_many(self, model: type[T], *, limit: int, offset: int, **kwargs: Any) -> list[T]: ...
    async def patch(self, model: type[T], pk: int, data: dict[str, Any]) -> T: ...
    async def count(self, model: type[T], **filters: Any) -> int: ...
